---
name: my_new_project
version: 1.0.0
config-version: 2
profile: default
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
target-path: target
clean-targets:
  - target
  - dbt_packages
sources:
  - name: elephantsql_source
    type: postgres
    host: trumpet.db.elephantsql.com
    port: 5432
    user: nfzuiloj
    password: 6Y83VSwHDSYP7Xct3XmDjaXDi_onP23Q
    database: nfzuiloj
    schema: public
    tables:
      - name: production_plan
        identifier: production_plan
      - name: manufacturing_units
        identifier: manufacturing_units
models:
  my_new_project:
    example:
      materialized: view
